### ISSUE TITLE
nil Pointer Problem

### ISSUE THREAD

**Issue by nazarifard** [ymz-ncnk/musgo#1]
It seems Musgo can't handle nil pointer, thus causes panic and invalid or nil pointer problem.
type Test struct {
   Ptr *int
} 
var test Test
test.Size()/test.MarshalMUS() will cause panic.

func (v Test) SizeMUS() int {
        size := 0
        {
                uv := uint64((*v.Ptr)<<1) ^ uint64((*v.Ptr)>>63)
                {
                        for uv >= 0x80 {
                                uv >>= 7
                                size++
                        }
                        size++
                }
        }
        return size
}
obviously, the generated code, doesn't handle nil pointer and will cause panic issue.

bahador.nazarifard@gmail.com

**Comment by ymz-ncnk** [comment]
This is predictable behavior. At [[musgen](https://github.com/ymz-ncnk/musgen)](https://github.com/ymz-ncnk/musgen) you can find: Nil pointers are not supported. Encoding will crash if meets a nil pointer.

**Comment by ymz-ncnk** [comment]
Depends on https://github.com/ymz-ncnk/musgen/issues/2.
