### ISSUE TITLE
Checksum?

### ISSUE THREAD

**Issue by kondratev** [ymz-ncnk/musgo#3]
Good idea, i think, adding a checksum to serdes. Perhaps this will allow you to find data errors without using validation or/and do validation when errors are found only.

Useful code, thanks

**Comment by ymz-ncnk** [comment]
I'm glad you find it useful.

It seems to me, that checksum can only guarantee data integrity, not correctness. That is, you still have to do data validation.

Could you give an example?

**Comment by kondratev** [comment]
If the data comes from untrusted sources it is correct to validate them. But, if the data comes from a trusted (local storage) source, we must be sure that it is not broken and only.

**Comment by ymz-ncnk** [comment]
A few thoughts on the scenario you described.

If we imagine that data gets into the local storage from an untrusted source, then this data in one situation should 
be validated, and in the other - should not. It would be nice if we could make an alias to our data type with validation 
turned off. At the moment, you can't do this for structures, but it could be quite easily implemented. What do you think 
about this?

As for checksum, I don't think adding it to the MUS format is a good idea:
1. This is not a general case. In other cases checksum could be handled, for
   example, by transport protocol.
2. This functionality can be easily implemented above musgo or any other
   serializer.
3. It doesn't give any performance benefits.

**Comment by kondratev** [comment]
I suggested using checksums as an addition to existing mus/unsafe mus. Not as a replacement.

The scenario I describe involves protection from data corruption where validation is too expensive.

Thanks again
